// LET OP: automatisch gegenereerd door sync-brief.py — niet met de hand aanpassen.
// De bron is build_letter.py in de projectmap; draai `python3 sync-brief.py` na elke briefwijziging.
// {{LINK}} wordt in brief.astro vervangen door siteUrl (of weggelaten als die leeg is).
export const aanhef = 'Beste Michiel,';

export const alineas = [
  'Graag reageer ik op de interne interessepeiling voor Coördinator AMMA. Bij mij thuis nemen boeken over communicatie, motivatie en organisatie bijna evenveel plankruimte in als mijn partituren; mijn favoriet is The Culture Map van Erin Meyer, over culturele verschillen in samenwerking. Bij AMMA komen twee instellingen met elk een eigen werkwijze samen; de praktische zaken daartussen wil ik zo regelen dat studenten ruimte houden voor de inhoud. Binnen het conservatorium werk ik breed: als docent en correpetitor over afdelingen heen, en sinds dit jaar als voorzitter van de AR/OC ook met het conservatorium als geheel.',
  'Voor circa vijftig studenten per jaar, binnen en buiten het ODM, ben ik het eerste aanspreekpunt voor lestijden, aanwezigheid en inhoudelijke vragen. Mijn deur en Teams staan open; zit iemand vast, dan help ik liever meteen dan te wachten tot het volgende contactmoment. Studentgericht werken betekent voor mij ook nauwkeurig bijhouden waar iemand staat. De voortgang leg ik systematisch vast in een eigen, gedocumenteerd systeem. Binnen een uur na een les staan de aantekeningen klaar, met concrete doelen voor de week erna. Dat systeem wil ik doorontwikkelen tot een webapp; een eerste interactieve proef voor studenten en docenten is via de link bovenaan deze brief te bekijken.',
  'Het administratieve deel van deze functie ligt mij. Als secretaris van de ondernemingsraad bij Platform C (2021–2025) beheerde ik de in- en uitgaande post, de agenda, de notulen en het archief, en bewaakte ik de deadlines. In mijn beroepspraktijk werk ik dagelijks met meerdere mailboxen naast elkaar: van contact met studenten tot externe partners in mijn freelance- en bestuurswerk. Vanuit de AR/OC ben ik vertrouwd met de OER van het CvA en met de regels rond studiepunten en toetsing, wat van pas komt wanneer behaalde punten hun weg moeten vinden naar het programma aan de andere instelling. Een student die aan de andere instelling een vak volgt, meldt zich bij beide aan, met termijnen die niet vanzelf gelijklopen. Daar wil een student duidelijkheid, op tijd en op één plek.',
  'Een groot deel van mijn werk is informatievoorziening: als docent breng ik iets ingewikkelds terug tot wat iemand op dat moment nodig heeft, precies de vertaalslag die de aanmeldperiodes vragen.',
  'Als projectleider van de herziening van de hoofdinstrumentmodule binnen het ODM (2025) bracht ik negentien hoofdvakdocenten met uiteenlopende achtergronden en werkwijzen tot één gedragen eindversie, met ruimte voor ieders inhoudelijke perspectief. Werkt een bestaand proces goed, dan laat ik het overigens staan.',
  'De overgangstentamens binnen het ODM heb ik sinds mijn indiensttreding bij het CvA in 2023 opnieuw opgezet. Voorheen vonden ze plaats in lesruimtes, met instrumenten bij elkaar waar dat logistiek uitkwam. Ik maakte er meerdere voorspeelmomenten met publiek van en meng de instrumenten bewust om samenwerking tussen studenten te stimuleren en het niveau te verhogen. Met het studiesecretariaat plan ik de commissies; als commissievoorzitter verwerk ik de feedback en cijfers.',
  'Voor de open dag van het ODM in seizoen 25/26 droeg ik zowel de logistieke als de inhoudelijke verantwoordelijkheid. Ik maakte het draaiboek en het presentatiemateriaal, stemde de huisstijl af met Communicatie en de inhoud en uitvoering met de ODM-coördinatoren. Ik benaderde docenten voor demonstratielessen en studenten die meehielpen, en presenteerde op de dag zelf. Het contact met Communicatie is daarna gebleven, ook via mijn werk in de AR/OC en onder meer via de informele lunch die ik elk kwartaal voor het ODM-team kook en waarvoor ik ook andere afdelingen uitnodig.',
  'Wat mij inhoudelijk in AMMA aanspreekt, is de directe verbinding tussen muziekpraktijk en onderzoek. In mijn masterscriptie over podiumpresentatie en muziekcognitie onderzocht ik zelf een vraag op dat snijvlak. Diezelfde verbinding zie ik in de keuzevakken Muziekwetenschap die meetellen in het conservatoriumcurriculum en in de twee seminars waarin studenten uit verschillende opleidingen samenkomen.',
  'Qua omvang past deze functie van 0,1 fte goed naast mijn huidige aanstelling. Ik ken het CvA sinds 2013 als student en sinds 2023 als medewerker. Ik ben er viereneenhalve dag per week aanwezig en weet daardoor snel wie ik waarvoor moet hebben. Ik licht mijn motivatie graag toe in een gesprek begin oktober.',
];

export const afsluiting = 'Met hartelijke groet,';
export const naam = 'Stephanus Harsono';
