// LET OP: automatisch gegenereerd door sync-brief.py — niet met de hand aanpassen.
// De bron is build_letter.py in de projectmap; draai `python3 sync-brief.py` na elke briefwijziging.
// {{LINK}} wordt in brief.astro vervangen door siteUrl (of weggelaten als die leeg is).
export const aanhef = 'Beste Michiel,';

export const alineas = [
  'Graag reageer ik op de interne interessepeiling voor Coördinator AMMA. Bij mij thuis vullen boeken over menselijk gedrag, communicatie en organisatie bijna meer planken dan mijn partituren. Die belangstelling voor mensen en organisatie loopt ook door mijn werk aan het CvA. Bij AMMA wil ik de praktische kant van studeren aan twee instellingen samenbrengen, zodat de student zich met de inhoud bezig kan houden. Ik werk breed binnen het conservatorium: als docent en correpetitor over afdelingen heen, en vanuit de AR/OC, waarvan ik sinds dit jaar voorzitter ben, met het conservatorium als geheel.',
  'Voor de circa vijftig studenten die ik jaarlijks begeleid, binnen en buiten het ODM, ben ik het eerste aanspreekpunt: voor lestijden en aanwezigheid, en voor inhoudelijke vragen. Mijn deur en mijn Teams staan daarvoor open. Komt een student er zelf uit, dan is dat het beste. Zit iemand vast, dan help ik die student liever meteen verder dan dat ik tot het volgende moment wacht. Studentgericht werken betekent voor mij ook nauwkeurig bijhouden waar iemand staat: de voortgang van elke student leg ik systematisch vast in een eigen, gedocumenteerd systeem, waarbij binnen een uur na een les de aantekeningen klaarstaan, met concrete doelen voor de week erna. Op termijn wil ik dat doorontwikkelen tot een webapp voor studenten en docenten.',
  'Het administratieve deel van deze functie ligt mij. Als secretaris van de ondernemingsraad bij Platform C (2021–2025) beheerde ik de in- en uitgaande post, de agenda, de notulen en het archief, en bewaakte ik de deadlines. In mijn beroepspraktijk werk ik dagelijks met meerdere mailboxen naast elkaar: van contact met studenten tot externe partners in mijn freelance- en bestuurswerk. Vanuit de AR/OC ben ik vertrouwd met de OER van het CvA en met de regels rond studiepunten en toetsing, wat van pas komt wanneer behaalde punten hun weg moeten vinden naar het programma aan de andere instelling. Een student die aan de andere instelling een vak volgt, meldt zich bij beide aan, met termijnen die niet vanzelf gelijklopen. Daar wil een student duidelijkheid, op tijd en op één plek.',
  'Een groot deel van mijn werk is informatievoorziening: als docent breng ik iets ingewikkelds terug tot wat iemand op dat moment nodig heeft — precies de vertaalslag die de aanmeldperiodes vragen.',
  'Als projectleider van de herziening van de hoofdinstrumentmodule binnen het ODM (2025) bracht ik negentien hoofdvakdocenten met uiteenlopende achtergronden en werkwijzen tot één gedragen eindversie, met ruimte voor ieders inhoudelijke perspectief. Werkt een bestaand proces goed, dan laat ik het overigens staan.',
  'De overgangstentamens binnen het ODM heb ik sinds mijn indiensttreding bij het CvA (2023) opnieuw opgezet, met een planning die telkens vroeg in het jaar begint. Ze vonden voorheen in lesruimtes plaats, met instrumenten bij elkaar gezet waar dat logistiek uitkwam; nu zijn het meerdere voorspeelmomenten met publiek, waarbij ik de instrumenten bewust meng om samenwerking tussen studenten te stimuleren en het niveau te verhogen. De beschikbaarheid van commissieleden stem ik af met het studiesecretariaat; als commissievoorzitter verzamel en verwerk ik de feedback en voer ik de cijfers in.',
  'Voor de open dag van het ODM van seizoen 25/26 maakte ik het draaiboek en verzorgde ik het presentatiemateriaal, in afstemming met de afdeling Communicatie over de huisstijl. Ik benaderde docenten voor demonstratielessen en ODM-studenten die meehielpen, en presenteerde op de dag zelf. Wat er in de inforondes en de lesruimte gebeurde, was mijn verantwoordelijkheid. Het contact met Communicatie is daarna gebleven, onder meer via de informele lunch die ik elk kwartaal voor het ODM-team kook en waarvoor ik steeds ook andere afdelingen uitnodig.',
  'AMMA spreekt mij ook inhoudelijk aan. Ik heb het programma doorgenomen: de keuzevakken van Muziekwetenschap die meetellen in het conservatoriumcurriculum, en de twee seminars voor gemengde groepen. In mijn masterscriptie over podiumpresentatie en muziekcognitie onderzocht ik zelf een vraag op dat snijvlak van praktijk en onderzoek. Met de opleidingscoördinator Muziekwetenschap heb ik nog geen contact gehad; dat zou ik als eerste willen leggen, naast het studiesecretariaat aan beide kanten. Wat ik als coördinator wil bereiken, is dat een student die ruimte kan verkennen zonder dat de praktische kant in de weg zit.',
  'Qua omvang past deze functie van 0,1 fte goed naast mijn huidige aanstelling. Ik ben viereneenhalve dag per week op het CvA aanwezig en ken het huis van binnenuit, eerst als student sinds 2013 en sinds 2023 als medewerker; dat netwerk betekent dat ik weet wie ik waarvoor moet hebben. Ter aanvulling op deze brief heb ik een korte webpagina gemaakt met mijn achtergrond en werk{{LINK}}. Ik licht mijn motivatie graag toe in een gesprek begin oktober.',
];

export const afsluiting = 'Met hartelijke groet,';
export const naam = 'Stephanus Harsono';
